### ISSUE TITLE
Please enable GitHub pages

### ISSUE THREAD

**Issue by mickaelistria** [rgrunber/eclipse.jdt.ls.client#4]
A p2 repo is already published on the gh-pages branch. Please enable pages so it can be served as HTTPS.

**Comment by rgrunber** [comment]
I've enabled the feature on th `gh-pages` branch, but don't see the page yet.

One thing to consider. While Github Pages does have limits, https://docs.github.com/en/pages/getting-started-with-github-pages/about-github-pages#usage-limits . you can deploy a p2 repo through GitHub Releases, if you modify the `artifacts.jar` so that instead of pointing to the artifacts under a sub-folder (eg. `plugins/`), you can flatten the repo, and have the artifacts at the root. The releases tab doesn't have the same limitations.

**Comment by rgrunber** [comment]
Nevemind, it's up :

```
$ p2ql https://rgrunber.github.io/eclipse.jdt.ls.client/ whatprovides ".*osgi.bundle.*"
IU: org.eclipse.jdt.ls.client 0.1.0.202211172130
* osgi.bundle; version:OSGiVersion=0.1.0.202211172130; osgi.bundle:String=org.eclipse.jdt.ls.client
* osgi.identity; osgi.identity:String=org.eclipse.jdt.ls.client; type:String=osgi.bundle; version:OSGiVersion=0.1.0.202211172130
```

**Comment by mickaelistria** [comment]
thanks!

**Comment by rgrunber** [comment]
@mickaelistria , if the repo ever gets bigger, I have a p2 repo (still up) at : https://github.com/rgrunber/eclipse.jdt.ls/releases/download/latest/ (ignore the 404, it is there) as a POC.

This is basically published via https://github.com/rgrunber/eclipse.jdt.ls/releases/ .
